#source common.sh
- name: Disable redis
  ansible.builtin.shell: dnf module disable redis -y

- name: Enable redis
  ansible.builtin.shell: dnf module enable redis:7 -y

- name: Install redis
  ansible.builtin.dnf: 
    name: redis
    state: latest
 
#update redis config
- name: Edit redis configuration
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Redis config update protected module
  ansible.builtin.lineinfile: 
    path: /etc/redis/redis.conf
    regexp: 'protected-mode'
    line: 'protected-mode no'

- name: Enable redis 
  ansible.builtin.systemd_service:
    name: redis
    state: restarted
    enable: yes