#source common.sh


- name: Installing mysql
  ansibe.builtin.dnf:
    name:  mysql-server 
    state: latest

- name: Enable- start Mysql
  ansibe.builtin.systemd_service:
    state: restarted
    enabled: true

# this will later on aws a service
- name: Setting mysql root password
  ansibe.builtin.shell: |
   mysql_secure_installation --set-root-pass {{secrets.MYSQL_ROOT_PASSWORD}}
