# - name: Run cart container
#   container.podman.podman_contianer:
#     name: cart
#     image: 
#     state: started
    # ports:
      # - "8080:8080"

- name: Run Dispatch container
  docker_container:
    name: dispatch
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/dispatch
    state: started
    ports:
      - "8080:8080"
    env: 
      AMQP_HOST: "{{secrets.AMQP_HOST}}"
      AMQP_USER: "{{secrets.AMQP_USER}}"
      AMQP_PASS: "{{secrets.AMQP_PASS}"
     