- name : Disable Nginx module
  ansible.builtin.command: 
    cmd: dnf module disable nginx -y
 

- name: Enable Nginx 24 version
  ansible.builtin.command:
    cmd: dnf module enable nginx:1.24 -y
  

- name: Install Nginx 
  ansible.builtin.dnf:
    name:  nginx
    state: latest
 

- name: Copy nginx config file
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  
# import from common-app prerequsites
- name: Common tasks
  ansible.builtin.include_role:
    name: common
    tasks_form: app-prereq

- name: Start nginx service
  ansible.builtin.systemd_service:
    state: restarted
    name: nginx
    enabled: true